version: '2'
services:
  mysql:
        image: mysql:8.0
        container_name: mysql-server1-80
        command: --default-authentication-plugin=mysql_native_password
        working_dir: /application
        volumes:
          - .:/application
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=kotka
          - MYSQL_DATABASE=geonames
          - MYSQL_USER=root
          - MYSQL_PASSWORD=kotka
        ports:
          - "8085:3306"
  website:
    container_name: php7-2
    build:
      context: ./
    links:
      - "mysql:database"
    volumes:
      - ./src:/var/www/html
    ports:
      - 8001:80
    depends_on:
      - mysql
